controllers/SiteController.php
<?php

namespace app\controllers;

use app\helpers\PaytabsHelper;
use app\models\Contracts;
use app\models\FreezeContract;
use app\models\Invoices;
use app\models\Payments;
use app\models\Reciepts;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Booking;
use app\models\BookingSearch;
use yii\helpers\Url;
use app\models\TermsAndConditions;

class SiteController extends DefaultController
{
    public $layout = 'login';
    public $enableCsrfValidation = false;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'index', 'flush-cache', 'test-email', 'fix-rec', 'logout', 'verify-payment', 'invoice-payment'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login', 'reset-password', 'forget-password', 'reset-password'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'verify-payment' => ['post'],
                    /* 'verify-payment' => ['get'],*/
                    //'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->checkLogin();
        //Yii::$app->cache->flush();
        $this->layout = 'main';
        $searchModel = new BookingSearch();
        $dataProvider = $searchModel->searchActive(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Flush Db Cache
     *
     * @return string
     */
    public function actionFlushCache()
    {
//		$this->checkLogin();
        Yii::$app->cache->flush();
        echo "Done";
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionFixRec($lastId = null)
    {
        $this->checkLogin();
        /*$results=Booking::find()
        ->select(['id','created_at'])
        ->andFilterWhere(['>','id',$lastId])
        ->orderBy(["id"=>SORT_ASC])
        ->asArray()->limit(200)->all();
        if($results!=null){
            foreach($results as $result){
                $lastId=$result['id'];
                $year = date('y', strtotime($result['created_at']));
                $reference='ECB'.'-'.$year.'-'.sprintf('%03d', $lastId);

                $connection = \Yii::$app->db;
                $connection->createCommand(
            "update ".Booking::tableName()." set reference_no=:reference_no where id=:id",
            [':reference_no'=>$reference, ':id'=>$lastId]
          )->execute();
            }
            echo '<script>window.location.href="'.Url::to(['site/fix-rec','lastId'=>$lastId]).'"</script>';
            exit;
        }else{
            echo "Finished";
            exit;
        }*/
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['site/index']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays forget page.
     *
     * @return Response|string
     */
    public function actionForgetPassword()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->sendEmail()) {
                echo "pass-sent";
                exit;
            } else {
                if ($model->hasErrors()) {
                    foreach ($model->getErrors() as $error) {
                        if (count($error) > 0) {
                            foreach ($error as $key => $val) {
                                Yii::$app->getSession()->addFlash('error', $val);
                            }
                        }
                    }
                }
            }
        }
        return $this->renderAjax('forget_password', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post())) {
            if ($model->resetPassword()) {
                Yii::$app->getSession()->addFlash('success', 'New password was saved.');
                return $this->redirect(['login']);
            } else {
                if ($model->hasErrors()) {
                    foreach ($model->getErrors() as $error) {
                        if (count($error) > 0) {
                            foreach ($error as $key => $val) {
                                Yii::$app->getSession()->addFlash('error', $val);
                            }
                        }
                    }
                }
            }
        }

        return $this->render('reset_password', [
            'model' => $model,
        ]);
    }

    public function actionTestEmail()
    {
        if (Yii::$app->mailer->compose()
            ->setFrom([Yii::$app->params['supportEmail'] => Yii::$app->params['siteName']])
            ->setTo(["malick.naeem@gmail.com" => "Naeem"])
            ->setSubject('Email Test from Elite Booking')
            ->setTextBody("This is email body using Elite Booking")
            ->send()
        ) {
            echo "Sent";
        } else {
            echo "Error!";
        }
    }

    public function actionDefTestEmail()
    {
        if (Yii::$app->defmailer->compose()
            ->setFrom([Yii::$app->params['supportEmail'] => Yii::$app->params['siteName']])
            ->setTo(["malick.naeem@gmail.com" => "Naeem"])
            ->setSubject('Email Test from Elite Booking')
            ->setTextBody("This is email body using Elite Booking")
            ->send()
        ) {
            echo "Sent";
        } else {
            echo "Error!";
        }
    }

    /**
     * @param string $invoice_id
     * @return string|Response
     */
    public function actionInvoicePayment($invoice_id = "")
    {

        if ($invoice_id) {
            \Yii::$app->session->set('payInvoiceId', $invoice_id);
        } else {
            if (Yii::$app->session->get('payInvoiceId')) {
                $invoice_id = \Yii::$app->session->get('payInvoiceId');
            } else {
                Yii::$app->session->setFlash('error', "Invoice number does not exists");
                return $this->goHome();
            }
        }

        if (isset($invoice_id) && !empty($invoice_id)) {

            $errors = [];
            $invoice = Invoices::findOne($invoice_id);
            $result = "";
            $title = "Invoice Payment";
            $prod_name = "Invoice Payment";

            if ($invoice <> null) {

                // If invoice is already paid
                if ($invoice->status == 'paid') {
                    \Yii::$app->session->setFlash('error', "This invoice is already paid");
                    return $this->redirect('/');
                }
                $prod_name = $invoice->invoice_description;
            } else {
                Yii::$app->session->setFlash('error', "Invoice is invalid!");
                return $this->goHome();
            }
           /* echo "<pre>";
            print_r($invoice);
            die;*/
            $paytabs = new PaytabsHelper();

            $resp = $paytabs->create_pay_page($invoice);
         /*   echo "<pre>";
            print_r($invoice);
            die;*/



            if (($resp <> null) && ($resp->response_code == '4012')) {

                //update user table
                $member = User::findOne($invoice->user_id);
                $member->p_id = $resp->p_id;
                $member->pay_page_url = $resp->payment_url;
                if (!$member->save()) {
                    return false;
                }
                //update invoice table
                $invoice->p_id = $resp->p_id;
                $invoice->pay_page_url = $resp->payment_url;
                if (!$invoice->save()) {
                    return false;
                }
            } else {
                $resp_err = $paytabs->responseCodes($resp->response_code);
                Yii::$app->getSession()->addFlash('error', Yii::t('app', $resp_err));
                return $this->redirect(Yii::$app->request->referrer ?: ['invoices/index']);
            }
            $this->redirect($resp->payment_url);
        }
    }

    /**
     * @param string $invoice_id

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

/* @var $this yii\web\View */

if (Yii::$app->user->identity->user_type != 0) {
    $this->title = 'Dashboard';
} else {
    $this->title = 'Dashboard - Upcoming Booking';
}
?>
<?php
if (Yii::$app->user->identity->user_type != 0){
$stats = Yii::$app->controller->adminStats;
?>
<div class="row">
    <a href="<?= Url::to(['booking/all']) ?>">
        <div class="col-xs-12 col-sm-3">
            <div class="info-box">
                <span class="info-box-icon bg-yellow"><i class="fa fa-star-o"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">All Bookings</span>
                    <span class="info-box-number"><?= $stats['allBookings'] ?></span>
                </div>
            </div>
        </div>
    </a>
    <a href="<?= Url::to(['booking/index']) ?>">
        <div class="col-xs-12 col-sm-3">
            <div class="info-box">
                <span class="info-box-icon bg-green"><i class="fa fa-calendar"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Future Bookings</span>
                    <span class="info-box-number"><?= $stats['futureBookings'] ?></span>
                </div>
            </div>
        </div>
    </a>
    <a href="<?= Url::to(['booking/history']) ?>">
        <div class="col-xs-12 col-sm-3">
            <div class="info-box">
                <span class="info-box-icon bg-navy"><i class="fa fa-bookmark-o"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Past Bookings</span>
                    <span class="info-box-number"><?= $stats['pastBookings'] ?></span>
                </div>
            </div>
        </div>
    </a>
    <a href="<?= Url::to(['package/index']) ?>">
        <div class="col-xs-12 col-sm-3">
            <div class="info-box">
                <span class="info-box-icon bg-maroon"><i class="fa fa-pie-chart"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Packages</span>
                    <span class="info-box-number"><?= $stats['allPackages'] ?></span>
                </div>
            </div>
        </div>
    </a>
    <a href="<?= Url::to(['city/index']) ?>">
        <div class="col-xs-12 col-sm-3">
            <div class="info-box">
                <span class="info-box-icon bg-red"><i class="fa fa-building"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Cities</span>
                    <span class="info-box-number"><?= $stats['allCities'] ?></span>
                </div>
            </div>
        </div>
    </a>
    <a href="<?= Url::to(['marina/index']) ?>">
        <div class="col-xs-12 col-sm-3">
            <div class="info-box">
                <span class="info-box-icon bg-aqua"><i class="fa fa-anchor"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Marina</span>
                    <span class="info-box-number"><?= $stats['allMarinas'] ?></span>
                </div>
            </div>
        </div>
    </a>
    <a href="<?= Url::to(['boat/index']) ?>">
        <div class="col-xs-12 col-sm-3">
            <div class="info-box">
                <span class="info-box-icon bg-purple"><i class="fa fa-ship"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Boats</span>
                    <span class="info-box-number"><?= $stats['allBoats'] ?></span>
                </div>
            </div>
        </div>
    </a>
    <a href="<?= Url::to(['member/index']) ?>">
        <div class="col-xs-12 col-sm-3">
            <div class="info-box">
                <span class="info-box-icon bg-blue"><i class="fa fa-users"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Members</span>
                    <span class="info-box-number"><?= $stats['allUsers'] ?></span>
                </div>
            </div>
        </div>
    </a>
    <a href="<?= Url::to(['contracts/comming-renewals']) ?>">
        <div class="col-xs-12 col-sm-3">
            <div class="info-box">
                <span class="info-box-icon bg-blue"><i class="fa fa-refresh"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Renewals( 30 days)</span>
                    <span class="info-box-number"><?= $stats['allCommingRenewals'] ?></span>
                </div>
            </div>
        </div>
    </a>
    <a href="<?= Url::to(['payment-cheques/comming-cheques']) ?>">
        <div class="col-xs-12 col-sm-3">
            <div class="info-box">
                <span class="info-box-icon bg-blue"><i class="fa fa-bank"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Cheques( 30 days)</span>
                    <span class="info-box-number"><?= $stats['allUpcomingCheques'] ?></span>
                </div>
            </div>
        </div>
    </a>
    <a href="<?= Url::to(['invoices/comming-invoices']) ?>">
        <div class="col-xs-12 col-sm-3">
            <div class="info-box">
                <span class="info-box-icon bg-blue"><i class="fa fa-money"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Invoices( 30 days)</span>
                    <span class="info-box-number"><?= $stats['allUpcomingInvoices'] ?></span>
                </div>
            </div>
        </div>
    </a>

</div>
</section>
<section class="content-header" style="padding-top:0px;">
    <h1>Upcoming Booking</h1>
</section>
<section class="content">
    <?php } ?>
    <div class="box box-success">
        <div class="box-body">
            <?php Pjax::begin(['id' => 'pjax-booking']); ?>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn', 'headerOptions' => ['class' => 'noprint', 'style' => 'width:10px;'],],
                    ['attribute' => 'city_id', 'value' => function ($model) {
                        return $model->city->title;
                    }],
                    ['attribute' => 'marina_id', 'value' => function ($model) {
                        return $model->marina->title;
                    }],
                    ['attribute' => 'boat_id', 'value' => function ($model) {
                        return $model->boat->title;
                    }],
                    'booking_date:date',
                    ['attribute' => 'time_slot_id', 'value' => function ($model) {
                        return $model->timeSlot->title;
                    }],
                    'txtAddons:raw',
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'header' => Yii::t('app', 'Actions'),
                        'headerOptions' => ['class' => 'noprint', 'style' => 'width:30px;'],
                        'contentOptions' => ['class' => 'noprint text-right'],
                        'template' => '{delete}',
                        'buttons' => [
                            'delete' => function ($url, $model) {
                                if (Yii::$app->user->identity->id == $model->user_id) {
                                    return Html::a('<i class="fa fa-remove"></i>', ['booking/delete', 'id' => $model->id], [
                                        'title' => Yii::t('app', 'Delete'),
                                        'data-toggle' => 'tooltip',
                                        'data-method' => 'post',
                                        'data-confirm' => Yii::t('app', 'Are you sure you want to delete this?'),
                                        'class' => 'btn btn-danger btn-xs',
                                    ]);
                                }
                            },
                        ],
                    ]
                ],
                'layout' => "{items}",
                'emptyText' => 'No future booking found!',
            ]); ?>
            <?php Pjax::end(); ?>
        </div>
    </div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
    <p class="login-box-msg">Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin(['id' => 'login-form',]); ?>
      <?= $form->field($model, 'username',['template'=>'
	  <div class="form-group has-feedback">
	  	{input}
		<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
		{error}{hint}
	  </div>
	  '])->textInput(['autofocus' => true, 'placeholder' => 'Username']) ?>
      <?= $form->field($model, 'password',['template'=>'
	  <div class="form-group has-feedback">
	  	{input}
		<span class="glyphicon glyphicon-lock form-control-feedback"></span>
		{error}{hint}
	  </div>
	  '])->passwordInput(['placeholder' => 'Password']) ?>
      <div class="row">
        <div class="col-xs-8">
          <?= $form->field($model, 'rememberMe')->checkbox()?>
        </div>
        <div class="col-xs-4">
          <?= Html::submitButton('Login', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
        </div>
      </div>
    </form>
    <?= '';//Html::a('I forgot my password',['site/forget-password'])?>
    <?php ActiveForm::end(); ?>
</div>