models/BookingForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * BookingForm is the model behind the booking search form.
 */
class BookingForm extends Model
{
    public $city_id;
    public $marina_id;
    public $date;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['city_id', 'marina_id', 'date'], 'required'],
            [['city_id','marina_id'], 'integer'],
            [['date'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
			'city_id' => Yii::t('app', 'City'),
			'marina_id' => Yii::t('app', 'Marina'),
			'date' => Yii::t('app', 'Date'),
		];
    }
}

controllers/BookingController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\BookingForm;
use app\models\Booking;
use app\models\BookingSearch;
use app\models\BoatSearch;
use app\models\Contracts;
use app\models\ContarctAddons;
use app\models\Addon;
use app\models\Invoices;
use app\models\InvoiceNumbers;
use app\helpers\HelperFunction;

use yii\web\NotFoundHttpException;

/**
 * BookingController implements the CRUD actions for Booking model.
 */
class BookingController extends DefaultController
{
    /**
     *
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index','all','history','create','load-boats','delete','createinvoice'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
				'denyCallback' => function ($rule, $action) {
					if(Yii::$app->request->isAjax){
						throw new \yii\web\HttpException(401, Yii::t('app','Please login.'));
					}else{
						return $this->redirect(['site/login']);
					}
				}
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Active Booking models.
     * @return mixed
     */
    public function actionIndex()
    {
		$this->checkLogin();
        $searchModel = new BookingSearch();
        $dataProvider = $searchModel->searchActive(Yii::$app->request->queryParams);
		$this->executeBulkAction();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Booking models.
     * @return mixed
     */
    public function actionAll($list='active')
    {
		$this->checkAdmin();
        $searchModel = new BookingSearch();
        $searchModel->listType=$list;
        $dataProvider = $searchModel->searchAll(Yii::$app->request->queryParams);
		$this->executeBulkAction();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
	
    /**
     * Run bulk action for bookings
     */
	public function executeBulkAction()
	{
		$action=Yii::$app->request->post('action');
		if($action!=null){
			if($action=="bdelete"){
				$selection=Yii::$app->request->post('selection');
				if($selection!=null){
					$connection = \Yii::$app->db;
					$connection->createCommand("update ".Booking::tableName()." set trashed='1',trashed_by='".Yii::$app->user->identity->id."',trashed_at='".date("Y-m-d H:i:s")."' where id in (".$selection.")")->execute();
        			Yii::$app->getSession()->addFlash('success', Yii::t('app','Selected bookings deleted successfully'));
					//return $this->redirect(Yii::$app->request->referrer ?: ['index'])->send();
				}
			}
		}
	}

    /**
     * Lists all Booking models.
     * @return mixed
     */
    public function actionHistory()
    {
		$this->checkLogin();
        $searchModel = new BookingSearch();
        $dataProvider = $searchModel->searchHistory(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Booking model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($city_id=null,$marina_id=null,$date=null)
    {
		$this->checkLogin();

		/*get current contract start*/
        $used_captain =  array();
        $used_food = array();
        $saved_addons =  array();
        $current_user = Yii::$app->user->identity->id ;
       /* echo $current_user;*/
        $member =User::find()->where(['id' => $current_user])->one();

        $current_contract = Contracts::find()->where([
            'user_id' => $current_user,
            'status' => 'active'
        ])->orderBy(['id' => SORT_DESC])->one();
      /*  echo "<pre>";
        print_r($current_contract);
        die;*/
        if($current_contract <>  null) {
            $used_captain =  Booking::find()->where(['contract_id' => $current_contract->id,'captain' => 1,'trashed' => 0])->asArray()->all();
            $used_food =  Booking::find()->where(['contract_id' => $current_contract->id,'food' => 2,'trashed' => 0])->asArray()->all();
            $used_donuts =  Booking::find()->where(['contract_id' => $current_contract->id,'donut' => 4,'trashed' => 0])->asArray()->all();

            $saved_addons = ContarctAddons::find()->where(['contract_id' => $current_contract->id])->asArray()->all();
            foreach ($saved_addons as $key =>  $addon){

                $saved_addons[$key]['addon_title'] = Addon::find()->where(['id' => $addon['addon_id']])->orderBy(['title' => SORT_ASC])->one()->title;
                $saved_addons[$key]['addon_price'] = Addon::find()->where(['id' => $addon['addon_id']])->orderBy(['title' => SORT_ASC])->one()->price;
                if($addon['addon_id'] == 1){
                    $saved_addons[$key]['addon_used'] = count($used_captain);
                }
                if($addon['addon_id'] == 2){
                    $saved_addons[$key]['addon_used'] = count($used_food);
                }
                if($addon['addon_id'] == 4){
                    $saved_addons[$key]['addon_used'] = count($used_donuts);
                }
            }
        }
        /*get current contract end*/

        $modelForm = new BookingForm();
		$model = new Booking();
		if($model->load(Yii::$app->request->post())) {

			$model->user_id=Yii::$app->user->identity->id;
			if(isset($current_contract->id)) {
                $model->contract_id = $current_contract->id;
            }



			if($model->save()){
				$model->sendBookingEmail();
        		Yii::$app->getSession()->addFlash('success', Yii::t('app','Booking saved successfully'));
				echo 'done';
				exit;
			}else{
				$errMsg='';
				if($model->getErrors()){
					foreach($model->getErrors() as $error){
						if(count($error)>0){
							foreach($error as $key=>$val){
								if($errMsg!='')$errMsg.='<br />';
								$errMsg.=$val;
							}
						}
					}
				}
				echo $errMsg;
				exit;
			}
		}
		$searchModel=[];
		$dataProvider=[];
        if ($modelForm->load(Yii::$app->request->post())) {
            $searchModel = new BoatSearch();
			$searchModel->city_id=$modelForm->city_id;
			$searchModel->marina_id=$modelForm->marina_id;
			$searchModel->status=1;
			$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        }

        return $this->render('create', [
            'modelForm' => $modelForm,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'city_id' => $city_id,
            'marina_id' => $marina_id,
            'date' => $date,
            'saved_addons' => $saved_addons,
            'contract' => $current_contract,
            'member' => $member,
        ]);
    }

    /**
     * Deletes an existing Booking model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
		$this->checkLogin();
        $this->findModel($id)->softDelete();
        Yii::$app->getSession()->addFlash('success', Yii::t('app','Record deleted successfully'));
        return $this->redirect(Yii::$app->request->referrer ?: ['index']);
    }


    public function actionCreateinvoice()
    {

        if(Yii::$app->request->post()) {

            $post = Yii::$app->request->post();

            //Create Invoice
            $invoice = new Invoices();

            $last_invoice_number = 0;
            $invoice_number = InvoiceNumbers::find()->orderBy(['id' => SORT_DESC])->one();
            if ($invoice_number <> null) {
                $last_invoice_number = $invoice_number->number;
            }
            $price = $post['Addon']['total'];


            $vat = HelperFunction::calculate_vat($price);

            $invoice->user_id = $post['Addon']['user_id'];
            $invoice->invoice_id = $last_invoice_number + 1;  //TODO: create a table and get inovice number from there
            $invoice->contract_id = $post['Addon']['contract_id'];

            $invoice->invoice_date = date('Y-m-d');
            if($price > 0) {
            $invoice->subtotal = (string)$price;
            $invoice->tax = (string)$vat;
            $invoice->total = (string)($price + $vat);
            }else{
                $invoice->subtotal =  "0";
                $invoice->tax =  "0";
                $invoice->total = "0";
                $price = "0";
            }
            $invoice->status = "pending";
            $invoice->created_by = $post['Addon']['user_id'];
            $invoice->invoice_description = "";
            $invoice->last_payment_date = "";
            $invoice->type = "addon";
            $invoice->addon_id = $post['Addon']['addon_id'];
            $invoice->billing_cycle = '1';

            if (!$invoice->save()) {
                return false;
            }else {

                $contract_addon = ContarctAddons::find()->where(['addon_id' => $post['Addon']['addon_id'], 'contract_id' => $post['Addon']['contract_id']])->one();
                if(!empty($contract_addon)) {
                    $contract_addon->qunatity = $contract_addon->qunatity + 1;
                    // $contract_addon->save();
                    if (!$contract_addon->save()) {
                        return false;
                    } else {

views/booking/_create.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\City;
use app\models\Marina;
use yii\web\JqueryAsset;

/* @var $this yii\web\View */
/* @var $model app\models\Booking */
/* @var $form yii\widgets\ActiveForm */

$this->registerCssFile('@web/'.'plugins/datepicker/datepicker3.css', ['depends' => [JqueryAsset::className()]]);
$this->registerJsFile('@web/'.'plugins/datepicker/bootstrap-datepicker.js', ['depends' => [JqueryAsset::className()]]);

$this->title = Yii::t('app', 'Book Boat');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Bookings'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$defMarina=[];
$jScript='var cities = []';
$cities=City::find()->where(['status'=>1,'trashed'=>0])->asArray()->all();
if($cities!=null){
	foreach($cities as $city){
		$jScript.='
			var city_'.$city['id'].' = [
		';
		$marinas=Marina::find()->where(['city_id'=>$city['id'],'status'=>1,'trashed'=>0])->orderBy('title')->asArray()->all();
		if($marinas!=null){
			foreach($marinas as $marina){
				$jScript.='{display: "'.$marina['title'].'", value: "'.$marina['id'].'"},';
			}
		}
		$jScript.=']';
	}
}
if($modelForm->city_id!=null){
	$defMarina=ArrayHelper::map(Marina::find()->where(['city_id'=>$modelForm->city_id,'status'=>1,'trashed'=>0])->orderBy('title')->asArray()->all(),'id','title');
}
$this->registerJs($jScript.'
	$("#bookingform-city_id").change(function() {
		cval=$(this).val();
		$("#bookingform-marina_id").html("");
		array_list=eval("city_"+cval)
		$(array_list).each(function (i) {
			$("#bookingform-marina_id").append("<option value=\""+array_list[i].value+"\""+(array_list[i].sel!="" ? array_list[i].sel : "")+">"+array_list[i].display+"</option>");
		});
	});
	$(".dtpicker").datepicker({
		format: "yyyy-mm-dd",
		todayHighlight: true,
		startDate: "today",
		
	}).on("changeDate", function(e) {
		$(this).datepicker("hide");
	});
');
?>
<div class="bookingform-create">
	<?php $form = ActiveForm::begin(); ?>
	<div class="bookingform-form box">
        <div class="box-body">
			<div class="row">
            	<div class="col-xs-12 col-sm-3"><?= $form->field($modelForm, 'city_id')->dropDownList(ArrayHelper::map($cities,'id','title'),['prompt'=>Yii::t('app','Select')]) ?></div>
            	<div class="col-xs-12 col-sm-3"><?= $form->field($modelForm, 'marina_id')->dropDownList($defMarina,['prompt'=>Yii::t('app','Select')]) ?></div>
                <div class="col-xs-12 col-sm-3"><?= $form->field($modelForm, 'date',['template'=>'
				  {label}
				  <div class="form-group has-feedback">
					{input}
					<span class="glyphicon glyphicon-calendar form-control-feedback"></span>
					{error}{hint}
				  </div>
				  '])->textInput(['class'=>'form-control dtpicker', 'readonly'=>'readonly']) ?></div>
                <div class="col-xs-12 col-sm-3"><?= Html::submitButton('Search', ['class' => 'btn btn-success btn-block', 'style'=>'margin-top:25px;']) ?></div>
            </div>
        </div>
    </div>
    <div id="boats-area" style="margin-top:20px;"></div>
    <?php ActiveForm::end(); ?>
</div>
<script type="text/javascript">
function loadBoats()
{
	if($("#booking-city_id").val()==""){
		swal('Information missing','Select City','info');
		return false;
	}
	if($("#booking-marina_id").val()==""){
		swal('Information missing','Select Marina','info');
		return false;
	}
	if($("#booking-booking_date").val()==""){
		swal('Information missing','Select Date','info');
		return false;
	}
	city_id=$("#booking-city_id").val();
	marina_id=$("#booking-marina_id").val();
	booking_date=$("#booking-booking_date").val();
	if(city_id!='' && marina_id!='' && booking_date!=''){
		$.ajax({
			url: "<?= Url::to(['booking/load-boats','city_id'=>'']);?>"+city_id+"&marina_id="+marina_id+"&booking_date="+booking_date,
			dataType: "html",
			success: function(html) {
				$("#boats-area").html(html);
			},
			error: bbAlert
		});
	}
}
</script>

views/booking/create.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\City;
use app\models\Marina;
use yii\web\JqueryAsset;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model app\models\Booking */
/* @var $form yii\widgets\ActiveForm */

$this->registerCssFile('@web/'.'plugins/datepicker/datepicker3.css', ['depends' => [JqueryAsset::className()]]);
$this->registerJsFile('@web/'.'plugins/datepicker/bootstrap-datepicker.js', ['depends' => [JqueryAsset::className()]]);

$this->title = Yii::t('app', 'Book Boat');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Bookings'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$defMarina=[];
$jScript='var cities = []';

$current_user = Yii::$app->user->identity->id ;
$current_contract = \app\models\Contracts::find()->where([
    'user_id' => $current_user,
    'status' => 'active'
])->orderBy(['id' => SORT_DESC])->one();


$city_ids = array();
if(!empty($current_contract)) {
    if ($current_contract->contractCities <> null && !empty($current_contract->contractCities)) {
        foreach ($current_contract->contractCities as $city) {
            $city_ids[] = $city->city_id;
        }
    }
}
if(!empty($city_ids)) {
    $cities = City::find()->where(['status' => 1, 'trashed' => 0, 'id' => $city_ids])->asArray()->all();
}else{
    $cities = City::find()->where(['status' => 1, 'trashed' => 0, 'id' => [1]])->asArray()->all();
}

//$cities=City::find()->where(['status'=>1,'trashed'=>0])->asArray()->all();
if($cities!=null){
    foreach($cities as $city){
        $jScript.='
			var city_'.$city['id'].' = [
		';
        $marinas=Marina::find()->where(['city_id'=>$city['id'],'status'=>1,'trashed'=>0])->orderBy('title')->asArray()->all();
        if($marinas!=null){
            foreach($marinas as $marina){
                $jScript.='{display: "'.$marina['title'].'", value: "'.$marina['id'].'"},';
            }
        }
        $jScript.=']';
    }
}
if($modelForm->city_id!=null){
    $defMarina=ArrayHelper::map(Marina::find()->where(['city_id'=>$modelForm->city_id,'status'=>1,'trashed'=>0])->orderBy('title')->asArray()->all(),'id','title');
}
$this->registerJs($jScript.'
	$("#bookingform-city_id").change(function() {
		cval=$(this).val();
		$("#bookingform-marina_id").html("");
		array_list=eval("city_"+cval)
		$(array_list).each(function (i) {
			$("#bookingform-marina_id").append("<option value=\""+array_list[i].value+"\""+(array_list[i].sel!="" ? array_list[i].sel : "")+">"+array_list[i].display+"</option>");
		});
	});
	$(".dtpicker").datepicker({
		format: "yyyy-mm-dd",
		todayHighlight: true,
		startDate: "'.(Yii::$app->user->identity->user_type==0 ? date("Y-m-d",mktime(0,0,0,date("m"),(date("d")+1),date("Y"))) : date("Y-m-d",mktime(0,0,0,date("m"),date("d"),date("Y")))).'",
		
	}).on("changeDate", function(e) {
		$(this).datepicker("hide");
	});
	
	$(".box-solid").find(".timings").css("height",Math.max.apply(Math, $(".box-solid .timings").map(function() { return $(this).height(); }))+"px");
');
?>
<div class="bookingform-create">
    <div class="bookingform-form box">
        <div class="box-body">
            <?php $form = ActiveForm::begin(); ?>
            <div class="row">

                <div class="col-xs-12 col-sm-3"><?= $form->field($modelForm, 'city_id')->dropDownList(ArrayHelper::map($cities,'id','title'),['prompt'=>Yii::t('app','Select')]) ?></div>
                <div class="col-xs-12 col-sm-3"><?= $form->field($modelForm, 'marina_id')->dropDownList($defMarina,['prompt'=>Yii::t('app','Select')]) ?></div>
                <div class="col-xs-12 col-sm-3"><?= $form->field($modelForm, 'date',['template'=>'
				  {label}
				  <div class="form-group has-feedback">
					{input}
					<span class="glyphicon glyphicon-calendar form-control-feedback"></span>
					{error}{hint}
				  </div>
				  '])->textInput(['class'=>'form-control dtpicker', 'readonly'=>'readonly']) ?></div>
                <div class="col-xs-12 col-sm-3"><?= Html::submitButton('Search', ['class' => 'btn btn-success btn-block', 'style'=>'margin-top:25px;']) ?></div>
            </div>
            <?php ActiveForm::end(); ?>

            <?php

            /*  echo "<pre>";
              print_r($saved_addons);
              die;*/
            $captain_disable = '';
            $food_disable = '';
            if(!empty($saved_addons)){
                $captain_availability =  $saved_addons[0]['qunatity'] - $saved_addons[0]['addon_used'];
                $food_availability =  $saved_addons[1]['qunatity'] - $saved_addons[1]['addon_used'];
                if($captain_availability > 0){
                    $captain_disable = '';
                }else{
                    $captain_disable =' disabled="disabled"';
                }
                if($food_availability > 0){
                    $food_disable = '';
                }else{
                    $food_disable =' disabled="disabled"';
                }
                ?>
                <div class="col-xs-12 col-sm-6">
                    <h3>Addons</h3>
                    <table style="width:100%">
                        <tr>
                            <th></th>
                            <th>Total</th>
                            <th>Availability</th>

                        </tr>
                        <!--  <tr>
                        <th>Captains</th>
                        <td><?/*= $saved_addons[0]['qunatity']; */?> </td>
                        <td><?/*= $captain_availability */?> </td>

                    </tr>-->
                        <tr>

                            <th>Food(Lunch/Dinner)</th>
                            <td><?= $saved_addons[1]['qunatity']; ?> </td>
                            <td><?= $food_availability ?> </td>

                        </tr>

                    </table>

                </div>
            <?php } ?>
        </div>
    </div>
    <div id="boats-area" style="margin-top:20px;">
        <?php
        if($searchModel!=null){
            echo ListView::widget( [
                'dataProvider' => $dataProvider,
                'viewParams' => ['city_id'=>$searchModel->city_id,'marina_id'=>$searchModel->marina_id,'booking_date'=>$modelForm->date,'captain_disable'=>$captain_disable, 'food_disable'=> $food_disable, 'member'=> $member,'contract'=> $contract],
                'itemOptions' => ['class' => 'col-xs-12 col-sm-4'],
                'itemView' => '/boat/_item',
                'layout'=>"<div class=\"row\">{items}</div>",
                'emptyText' => '<div class="alert alert-danger">No results found!</div>'
            ] );
        }
        ?>
    </div>
</div>

views/booking/index.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use app\widgets\CustomGridView;
use app\models\City;
use app\models\Marina;
use app\models\Boat;
use app\models\TimeSlot;

/* @var $this yii\web\View */
/* @var $searchModel app\models\BookingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

if(Yii::$app->controller->action->id=='all'){
	if($searchModel->listType=='active'){
		$this->title = Yii::t('app', 'Future Bookings');
	}
	if($searchModel->listType=='old'){
		$this->title = Yii::t('app', 'Old Bookings');
	}
	if($searchModel->listType=='all'){
		$this->title = Yii::t('app', 'All Bookings');
	}
	if($searchModel->listType=='deleted'){
		$this->title = Yii::t('app', 'Deleted Bookings');
	}
}elseif(Yii::$app->controller->action->id=='history'){
	$this->title = Yii::t('app', 'Booking History');
}else{
	$this->title = Yii::t('app', 'Active Bookings');
}

$this->params['breadcrumbs'][] = $this->title;

$defMarina=Marina::find()->where(['status'=>1,'trashed'=>0])->orderBy('title')->asArray()->all();
if($searchModel->city_id!=null){
	$defMarina=Marina::find()->where(['city_id'=>$searchModel->city_id,'status'=>1,'trashed'=>0])->orderBy('title')->asArray()->all();
}
$defBoats=Boat::find()->where(['status'=>1,'trashed'=>0])->orderBy('title')->asArray()->all();
if($searchModel->marina_id!=null){
	$defMarina=Boat::find()->where(['marina_id'=>$searchModel->marina_id,'status'=>1,'trashed'=>0])->orderBy('title')->asArray()->all();
}

$columns[]=['class' => 'yii\grid\SerialColumn','headerOptions'=>['class'=>'noprint','style'=>'width:10px;'],];
if((Yii::$app->user->identity->user_type==1 || Yii::$app->user->identity->user_type==2)){
$columns[]=['class' => 'yii\grid\CheckboxColumn','checkboxOptions'=>function ($model, $key, $index, $column){return ['value' => $model->id, 'class'=>'cb'];},'contentOptions'=>['style'=>'width: 10px;']];
}
$columns[]='reference_no';
if((Yii::$app->user->identity->user_type==1 || Yii::$app->user->identity->user_type==2) && Yii::$app->controller->action->id=='all'){
$columns[] = 'userName';
}
if(Yii::$app->user->identity->user_type==0 && Yii::$app->user->identity->package_id==Yii::$app->params['goldenSharePackageId']){
$columns[] = 'userName';
}
$columns[]=['attribute'=>'city_id','value'=>function($model){return $model->city->title;},'filter'=>ArrayHelper::map(City::find()->where(['status'=>1,'trashed'=>0])->orderBy('title')->asArray()->all(),'id','title')];
$columns[]=['attribute'=>'marina_id','value'=>function($model){return $model->marina->title;},'filter'=>ArrayHelper::map($defMarina,'id','title')];
$columns[]=['attribute'=>'boat_id','value'=>function($model){return $model->boat->title;},'filter'=>ArrayHelper::map($defBoats,'id','title')];
$columns[]='booking_date:date';
$columns[]=['attribute'=>'time_slot_id','value'=>function($model){return $model->timeSlot->title;},'filter'=>ArrayHelper::map(TimeSlot::find()->where(['status'=>1,'trashed'=>0])->asArray()->all(),'id','title')];
$columns[]=['attribute'=>'captain','label' => 'Addons','value'=>function($model){
    $addons_text='';
    if(isset($model->captaindata->title) && isset($model->fooddata->title)){
        $addons_text .= $model->captaindata->title.', '.$model->fooddata->title;
    }else if(isset($model->captaindata->title)){
        $addons_text .= $model->captaindata->title;
    }else if(isset($model->fooddata->title)){
        $addons_text .= $model->fooddata->title;
    }

    return $addons_text;

}];
/*$columns[]='txtAddons:html';*/
if(Yii::$app->controller->action->id=='index' || Yii::$app->controller->action->id=='all'){
	$columns[]=[
		'class' => 'yii\grid\ActionColumn',
		'header'=>Yii::t('app','Actions'),
		'headerOptions'=>['class'=>'noprint','style'=>'width:30px;'],
		'contentOptions'=>['class'=>'noprint text-right'],
		'template' => '{delete}',
		'buttons' => [
			'delete' => function ($url, $model) {
				if(Yii::$app->user->identity->user_type==0 && Yii::$app->user->identity->id==$model->user_id){
    				return Html::a('<i class="fa fa-remove"></i>', $url, [
    					'title' => Yii::t('app', 'Delete'),
    					'data-toggle'=>'tooltip',
    					'data-method'=>'post',
    					'data-confirm'=>Yii::t('app','Are you sure you want to delete this?'),
    					'class'=>'btn btn-danger btn-xs',
    				]);
				}elseif(Yii::$app->user->identity->id==2){
					return Html::a('<i class="fa fa-remove"></i>', $url, [
						'title' => Yii::t('app', 'Delete'),
						'data-toggle'=>'tooltip',
						'data-method'=>'post',
						'data-confirm'=>Yii::t('app','Are you sure you want to delete this?'),
						'class'=>'btn btn-danger btn-xs',
					]);
				}
			},
		],
	];
}
?>
<?php if(Yii::$app->controller->action->id=='all'){?>
<?= Html::a('Future Bookings',['booking/all','list'=>'active'],['class'=>'btn btn-'.($searchModel->listType=='active' ? 'primary' : 'default').' btn-sm'])?> 
<?= Html::a('Old Bookings',['booking/all','list'=>'old'],['class'=>'btn btn-'.($searchModel->listType=='old' ? 'primary' : 'default').' btn-sm'])?> 
<?= Html::a('All Bookings',['booking/all','list'=>'all'],['class'=>'btn btn-'.($searchModel->listType=='all' ? 'primary' : 'default').' btn-sm'])?> 
<?= Html::a('Deleted Bookings',['booking/all','list'=>'deleted'],['class'=>'btn btn-'.($searchModel->listType=='deleted' ? 'primary' : 'default').' btn-sm'])?>
<?php }?>
<div class="booking-index">
    <?php
    if(Yii::$app->controller->action->id=='all'){
		echo CustomGridView::widget([
			'create'=>true,
			'bulkdelete'=>true,
			'dataProvider' => $dataProvider,
			'filterModel' => $searchModel,
			'columns' => $columns,
		]);
	}else{
		if(Yii::$app->controller->action->id=='index' && (Yii::$app->user->identity->user_type==1 || Yii::$app->user->identity->user_type==2)){
			echo CustomGridView::widget([
				'create'=>true,
				'bulkdelete'=>true,
				'dataProvider' => $dataProvider,
				'columns' => $columns,
			]);
		}else{
			echo CustomGridView::widget([
				'create'=>true,
				'dataProvider' => $dataProvider,
				'columns' => $columns,
			]);
		}
	}
	?>
</div>

views/booking/search.php
<?php
use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\BoatSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
echo ListView::widget( [
	'dataProvider' => $dataProvider,
	'viewParams' => ['city_id'=>$searchModel->city_id,'marina_id'=>$searchModel->marina_id,'booking_date'=>$booking_date],
	'itemOptions' => ['class' => 'col-xs-12 col-sm-4'],
	'itemView' => '/boat/_item',
	'layout'=>"<div class=\"row\">{items}</div>",
] );
?>